### ISSUE TITLE
Unclear error message (StringIndexOutOfBoundsException) when passing empty argument to --driver

### ISSUE THREAD

**Issue by arotenberg-google** [google/dwh-migration-tools#114]
Calling the dumper with `--driver ""` (e.g. due to a bad environment variable in the command line) throws an exception like:

```
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 0
    at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
    at java.base/java.lang.String.charAt(String.java:693)
    at com.google.edwmigration.dumper.application.dumper.JsonResponseFile.addResponseFiles(JsonResponseFile.java:61)
    at com.google.edwmigration.dumper.application.dumper.MetadataDumper.main(MetadataDumper.java:319)
```

This error message is unclear what the problem is, making it hard to debug.

**Comment by vladislav-sidorovich** [comment]
Currently error message is different, but the main idea of the issue is still valid.

**Comment by vladislav-sidorovich** [comment]
https://github.com/google/dwh-migration-tools/pull/579
