### ISSUE TITLE
org.apache.thrift.transport.TTransportException: MaxMessageSize reached

### ISSUE THREAD

**Issue by sguruprasad-google** [google/dwh-migration-tools#27]
Hi Team,

We are trying to use the Metadata dumper in a secured environment(without internet access).
We are facing below issue, please help us.

* What went wrong:
A problem occurred configuring project ':dumper:app'.
> Could not resolve all artifacts for configuration ':dumper:app:classpath'.
   > Could not resolve com.github.jk1:gradle-license-report:1.17.
     Required by:
         project :dumper:app
      > Could not resolve com.github.jk1:gradle-license-report:1.17.
         > Could not get resource 'https://plugins.gradle.org/m2/com/github/jk1/gradle-license-report/1.17/gradle-license-report-1.17.pom'.
            > Could not GET 'https://plugins.gradle.org/m2/com/github/jk1/gradle-license-report/1.17/gradle-license-report-1.17.pom'.
               > Connect to plugins.gradle.org:443 [plugins.gradle.org/104.18.191.9, plugins.gradle.org/104.18.190.9, plugins.gradle.org/2606:4700:0:0:0:0:6812:bf09, plugins.gradle.org/2606:4700:0:0:0:0:6812:be09] failed: Network is unreachable (connect failed)
> Could not get unknown property 'installPublishedDist' for task set of type org.gradle.api.internal.tasks.DefaultTaskContainer.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Thanks

**Comment by sguruprasad-google** [comment]
Hi @paolomorandini 

Thanks a lot for sharing the binary.
On using the packaged binary, i am facing below issue. Can we please get any suggestions on this.

05:59:11.350 [main] WARN com.google.edwmigration.dumper.application.dumper.MetadataDumper - Task failed: Write functions.csv from get_all_functions(): org.apache.thrift.transport.TTransportException: MaxMessageSize reached
org.apache.thrift.transport.TTransportException: MaxMessageSize reached
	at org.apache.thrift.transport.TEndpointTransport.checkReadBytesAvailable(TEndpointTransport.java:81)
	at org.apache.thrift.protocol.TBinaryProtocol.checkStringReadLength(TBinaryProtocol.java:443)
	at org.apache.thrift.protocol.TBinaryProtocol.readStringBody(TBinaryProtocol.java:414)
	at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:255)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:77)
	at com.google.edwmigration.dumper.ext.hive.metastore.thrift.api.superset.ThriftHiveMetastore$Client.recv_get_all_functions(ThriftHiveMetastore.java:4785)
	at com.google.edwmigration.dumper.ext.hive.metastore.thrift.api.superset.ThriftHiveMetastore$Client.get_all_functions(ThriftHiveMetastore.java:4773)
	at com.google.edwmigration.dumper.ext.hive.metastore.HiveMetastoreThriftClient_Superset.getFunctions(HiveMetastoreThriftClient_Superset.java:207)
	at com.google.edwmigration.dumper.application.dumper.connector.hive.HiveMetadataConnector$FunctionsTask.run(HiveMetadataConnector.java:192)
	at com.google.edwmigration.dumper.application.dumper.connector.hive.AbstractHiveConnector$AbstractHiveTask.doRun(AbstractHiveConnector.java:170)
	at com.google.edwmigration.dumper.application.dumper.connector.hive.AbstractHiveConnector$AbstractHiveTask.doRun(AbstractHiveConnector.java:154)
	at com.google.edwmigration.dumper.application.dumper.task.AbstractTask.run(AbstractTask.java:106)
	at com.google.edwmigration.dumper.application.dumper.MetadataDumper.runTask(MetadataDumper.java:135)
	at com.google.edwmigration.dumper.application.dumper.MetadataDumper.run(MetadataDumper.java:262)
	at com.google.edwmigration.dumper.application.dumper.MetadataDumper.run(MetadataDumper.java:108)
	at com.google.edwmigration.dumper.application.dumper.MetadataDumper.main(MetadataDumper.java:337)
05:59:11.491 [main] DEBUG com.google.edwmigration.dumper.application.dumper.MetadataDumper - Dumper wrote 27152 bytes.
05:59:11.492 [main] DEBUG com.google.edwmigration.dumper.application.dumper.MetadataDumper - Dumper took 810.4 ms.
**********************************************************
* Task Summary:
* Task FAILED (REQUIRED) Write functions.csv from get_all_functions(): org.apache.thrift.transport.TTransportException: MaxMessageSize reached
* Task SUCCEEDED (INFORMATIONAL) Write compilerworks-arguments.txt from command-line arguments.
* Task SUCCEEDED (REQUIRED) Write compilerworks-metadata.yaml containing dump metadata.
* Task FAILED (REQUIRED) Write schemata.csv from get_all_databases(): org.apache.thrift.transport.TTransportException: MaxMessageSize reached
* Task SUCCEEDED (REQUIRED) Write compilerworks-format.txt containing 'hiveql.dump.zip'.
* Task SUCCEEDED (INFORMATIONAL) Write compilerworks-version.txt from product version information.
* Task FAILED (REQUIRED) Write tables.jsonl from get_all_databases()*.get_all_tables()*.[.get_fields(),.get_partition_keys()]: org.apache.thrift.transport.TTransportException: MaxMessageSize reached
**********************************************************
* Metadata has been saved to dwh-migration-hiveql-metadata.zip
* To import this file, add the metadata line to your
* transpiler configuration:
*
    environment("my-environment-name", type: "hiveql") {
        metadata "dwh-migration-hiveql-metadata.zip"
    }
**********************************************************
* ERROR: 3 required task[s] failed.
* Output, including debugging information, has been saved to dwh-migration-hiveql-metadata.zip

**Comment by genemerrill** [comment]
@paolomorandini is this related to [thrift frame size](https://stackoverflow.com/questions/32552828/how-to-change-apache-thrift-frame-size/32566165#32566165)? If so is it possible to set a larger default when we build? Or if changing default is not the answer, provide a recipe for how customer can run a build specifying an increase?

**Comment by genemerrill** [comment]
Based on engineering investigating the frame size may not be the issue, FYI we are working on b/235577106 behind the scenes to fix.

**Comment by genemerrill** [comment]
@sguruprasad-google can you provide details on the Hive version? And confirm you are using v1.0.4 (or latest) version of metadata dumper release at https://github.com/google/dwh-migration-tools/releases/latest ?

**Comment by sguruprasad-google** [comment]
@genemerrill 
Below are the details
1. Hive version: 3.1.2

2. We are using the binary dwh-migration-tools-v1.0.3 from the below location:
https://github.com/google/dwh-migration-tools/releases/latest

**Comment by genemerrill** [comment]
Fixed in release [v1.0.7](https://github.com/google/dwh-migration-tools/releases/tag/v1.0.7)
